require:
  - rubocop-rspec

# Common configuration.
AllCops:
  Layout/LineLength:
    Max: 120

  Metrics/MethodLength:
    Max: 25

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 140

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

RSpec/MessageSpies:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false
